import Head from 'next/head'
import { DesignGridItem } from '../features/Design/presentation/DesignGridItem/DesignGridItem'
import { Grid } from '../components/layout/Grid/Grid'
import testImage from '../public/images/testdesign.png'

const Home = (): JSX.Element => {
  return (
    <div>
      <Head>
        <title>JORIS POGGIOLI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      {/* <Grid
        Component={DesignGridItem}
        gridItems={[
          {
            key: '1',
            gridColumn: '1',
            componentProps: {
              src: testImage,
              alt: 'testImage',
              name: 'CONSTANTIN CONSOLE',
            },
            hasBorderRight: true,
          },
          {
            key: '2',
            gridColumn: '2 / 3',
            componentProps: {
              src: testImage,
              alt: 'testImage',
              name: 'CONSTANTIN CONSOLE',
            },
            hasBorderRight: true,
          },
          {
            key: '2',
            gridColumn: '3 / 4',
            componentProps: {
              src: testImage,
              alt: 'testImage',
              name: 'CONSTANTIN CONSOLE',
            },
            hasBorderRight: true,
          },
          {
            key: '2',
            gridColumn: '1',
            componentProps: {
              src: testImage,
              alt: 'testImage',
              name: 'CONSTANTIN CONSOLE',
            },
            hasBorderRight: true,
            hideBorderBottom: true,
          },
        ]}
        gridTemplateColumns="repeat(3, 1fr)"
        gridAutoRows="600px"
      /> */}
    </div>
  )
}

export default Home
